### ISSUE TITLE
Async knihovny

### ISSUE THREAD

**Issue by Pablo2048** [rici4kubicek/room-thermostat#1]
Ahoj Richarde,
všiml jsem si, že používáš moje forky AsyncTCP a ESPAsyncWebServeru. Není to dobře - původní verze AsyncTCP a web serveru už se zdá, že nejsou udržované a tak jsem si udělal vlastní forky, do kterých jsem se snažil aplikovat známé opravy chyb. Bohužel zdaleka na všechny chyby byly opraveny a nakonec se objevily "remake" knihoven, které jsou podstatně stabilnější a já na ně přešel. Konkrétně se jedná o náhradu AsyncTCP, která se jmenuje AsyncTCPSock https://github.com/yubox-node-org/AsyncTCPSock a velké úpravy ESPAsyncWebServeru odsud https://github.com/yubox-node-org/ESPAsyncWebServer/tree/yuboxfixes-0xFEEDC0DE64-cleanup (POZOR!! je třeba použít přesně tento branch). Použitím těchto knihoven se výrazně zvýšila stabilita a spolehlivost.

**Comment by rici4kubicek** [comment]
Děkuji za upozornění.
